### ISSUE TITLE
scoop has a supabase app on the main bucket

### ISSUE THREAD

**Issue by chiptus** [supabase/scoop-bucket#26]
should we use the main bucket supabase? https://scoop.sh/#/apps?q=supabase&id=7e3b2237377863bf4f3376f2f01f2c178584de4d

or is it a fake and we should use the one in the docs?

**Comment by sweatybridge** [comment]
The main bucket was added by a maintainer of scoop and from the looks of it, the [manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/supabase.json) is the same as we have here.

It should be fine to use either bucket. Note that the main bucket may be a few hours behind after each release because it's updated separately by a github bot.
